<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            'Afghanistan',
            'South Africa (Republic of)',
            'Angola (Republic of)',
            'Albania (Republic of)',
            'Algeria (People\'s Democratic Republic of)',
            'Andorra (Principality of)',
            'Argentine Republic',
            'Armenia (Republic of)',
            'Saudi Arabia (Kingdom of)',
            'Antigua and Barbuda',
            'Australia',
            'Austria',
            'Azerbaijan (Republic of)',
            'Brazil (Federative Republic of)',
            'Bahamas (Commonwealth of the)',
            'Burundi (Republic of)',
            'Belgium',
            'Benin (Republic of)',
            'Burkina Faso',
            'Bangladesh (People\'s Republic of)',
            'Bahrain (Kingdom of)',
            'Bosnia and Herzegovina',
            'Belarus (Republic of)',
            'Belize',
            'Bolivia (Plurinational State of)',
            'Botswana (Republic of)',
            'Barbados',
            'Myanmar (Union of)',
            'Brunei Darussalam',
            'Bhutan (Kingdom of)',
            'Bulgaria (Republic of)',
            'Central African Republic',
            'Canada',
            'Cambodia (Kingdom of)',
            'Chile',
            'China (People\'s Republic of)',
            'Colombia (Republic of)',
            'Sri Lanka (Democratic Socialist Republic of)',
            'Cameroon (Republic of)',
            'Democratic Republic of the Congo',
            'Congo (Republic of the)',
            'Comoros (Union of the)',
            'Cabo Verde (Republic of)',
            'Côte d\'Ivoire (Republic of)',
            'Costa Rica',
            'Cuba',
            'Vatican City State',
            'Cyprus (Republic of)',
            'Czech Republic',
            'Germany (Federal Republic of)',
            'Djibouti (Republic of)',
            'Dominica (Commonwealth of)',
            'Denmark',
            'Dominican Republic',
            'Spain',
            'Egypt (Arab Republic of)',
            'Ecuador',
            'Eritrea',
            'Estonia (Republic of)',
            'Ethiopia (Federal Democratic Republic of)',
            'France',
            'Finland',
            'Fiji (Republic of)',
            'Micronesia (Federated States of)',
            'United Kingdom of Great Britain and Northern Ireland',
            'Gabonese Republic',
            'Georgia',
            'Ghana',
            'Gambia (Republic of the)',
            'Guinea-Bissau (Republic of)',
            'Equatorial Guinea (Republic of)',
            'Greece',
            'Grenada',
            'Guatemala (Republic of)',
            'Guinea (Republic of)',
            'Guyana',
            'Honduras (Republic of)',
            'Hungary',
            'Netherlands (Kingdom of the)',
            'Croatia (Republic of)',
            'Haiti (Republic of)',
            'Italy',
            'India (Republic of)',
            'Indonesia (Republic of)',
            'Ireland',
            'Iran (Islamic Republic of)',
            'Iraq (Republic of)',
            'Iceland',
            'Israel (State of)',
            'Japan',
            'Jamaica',
            'Jordan (Hashemite Kingdom of)',
            'Kazakhstan (Republic of)',
            'Kenya (Republic of)',
            'Kyrgyz Republic',
            'Kiribati (Republic of)',
            'Saint Kitts and Nevis (Federation of)',
            'Korea (Republic of)',
            'Democratic People\'s Republic of Korea',
            'Kuwait (State of)',
            'Lao People\'s Democratic Republic',
            'Lebanon',
            'Liberia (Republic of)',
            'Libya (State of)',
            'Saint Lucia',
            'Liechtenstein (Principality of)',
            'Lesotho (Kingdom of)',
            'Lithuania (Republic of)',
            'Luxembourg',
            'Latvia (Republic of)',
            'Mauritius (Republic of)',
            'Monaco (Principality of)',
            'Moldova (Republic of)',
            'Madagascar (Republic of)',
            'Mexico',
            'Marshall Islands (Republic of the)',
            'North Macedonia (Republic of)',
            'Malaysia',
            'Maldives (Republic of)',
            'Mali (Republic of)',
            'Malta',
            'Montenegro',
            'Mongolia',
            'Mozambique (Republic of)',
            'Morocco (Kingdom of)',
            'Mauritania (Islamic Republic of)',
            'Malawi',
            'Nicaragua',
            'Niger (Republic of the)',
            'Nigeria (Federal Republic of)',
            'Namibia (Republic of)',
            'Norway',
            'Nepal (Federal Democratic Republic of)',
            'Nauru (Republic of)',
            'New Zealand',
            'Oman (Sultanate of)',
            'Pakistan (Islamic Republic of)',
            'Philippines (Republic of the)',
            'Palau (Republic of)',
            'Papua New Guinea',
            'Panama (Republic of)',
            'Poland (Republic of)',
            'Portugal',
            'Paraguay (Republic of)',
            'Peru',
            'Qatar (State of)',
            'Romania',
            'Rwanda (Republic of)',
            'Russian Federation',
            'Sweden',
            'Sudan (Republic of the)',
            'Senegal (Republic of)',
            'Seychelles (Republic of)',
            'Solomon Islands',
            'El Salvador (Republic of)',
            'Samoa (Independent State of)',
            'San Marino (Republic of)',
            'Singapore (Republic of)',
            'Somalia (Federal Republic of)',
            'Serbia (Republic of)',
            'Sierra Leone',
            'South Sudan (Republic of)',
            'Sao Tome and Principe (Democratic Republic of)',
            'Switzerland (Confederation of)',
            'Suriname (Republic of)',
            'Slovak Republic',
            'Slovenia (Republic of)',
            'Eswatini (Kingdom of)',
            'Syrian Arab Republic',
            'Chad (Republic of)',
            'Togolese Republic',
            'Thailand',
            'Tajikistan (Republic of)',
            'Turkmenistan',
            'Timor-Leste (Democratic Republic of)',
            'Tonga (Kingdom of)',
            'Trinidad and Tobago',
            'Tunisia',
            'Republic of Türkiye',
            'Tuvalu',
            'Tanzania (United Republic of)',
            'United Arab Emirates',
            'Uganda (Republic of)',
            'Ukraine',
            'Uruguay (Eastern Republic of)',
            'United States of America',
            'Uzbekistan (Republic of)',
            'Saint Vincent and the Grenadines',
            'Venezuela (Bolivarian Republic of)',
            'Viet Nam (Socialist Republic of)',
            'Vanuatu (Republic of)',
            'Yemen (Republic of)',
            'Zambia (Republic of)',
            'Zimbabwe (Republic of)',
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert(['name' => $country]);
        }
    }
}
